system-config:
  httpDataEnable: false
  mqttDataEnable: false
  wsdjDataEnable: false
  windDataEnable: false
  daasDataEnable: false
  gnssDataEnable: false

mqtt-config:
  url: "124.71.85.153"
  port: 1883
  topic: $test
  username: admin
  password: public

logging:
  level:
    com.zd: debug
    org.springframework: warn

spring:
  datasource:
    url: jdbc:sqlite:./zd.db
    type: com.alibaba.druid.pool.DruidDataSource
    # druid相关配置
    druid:
    # 连接池初始化大小
      initial-size: 2
      # 最大活跃连接数
      max-active: 5
      # 最小空闲连接数
      min-idle: 1
      # 获取连接等待超时的时间
      max-wait: 60000
      # 间隔多久才进行一次检测，检测需要关闭的空闲连接，ms
      time-between-eviction-runs-millis: 60000

      validation-query: select 'x'
      # 配置过滤器，https://github.com/alibaba/druid/wiki/%E5%86%85%E7%BD%AEFilter%E7%9A%84%E5%88%AB%E5%90%8D
      filters: stat,slf4j,config
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: zd
        login-password: 123456
  profiles:
    active: @profiles.active@

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

radar:
  water:
    level:
      tcp:
        server:
          port: 41000
          max-connections: 15      # 调整为实际的客户端数量
          send-interval-ms: 60000   # 发送指令间隔（毫秒）
          receive-timeout-ms: 100  # 接收数据超时（毫秒）
server:
  port: 42009